// HoldSpace — Seed Data (Mock Healers)
import { Healer, Review } from "./constants";

export const SEED_HEALERS: Healer[] = [
    {
        id: "h-aria-moon",
        fullName: "Aria Moon",
        avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
        bio: "I hold space for grief, anxiety, and the heavy moments. Through breathwork and somatic release, we'll find stillness together. 8 years guiding people through their darkest seasons — you don't have to carry it alone.",
        modalities: ["breathwork", "grief-holding", "somatic"],
        certifications: ["Certified Breathwork Facilitator", "Somatic Experiencing Level II"],
        languages: ["English", "Spanish"],
        hourlyRate: 85,
        currency: "USD",
        availabilityStatus: "online",
        isVerified: true,
        yearsExperience: 8,
        avgRating: 4.92,
        totalReviews: 127,
        totalSessions: 340,
        trustScore: 88,
        trustTier: "trusted",
        identityVerified: true,
        credentialsVerified: true,
        backgroundCheck: true,
        cancellationRate: 0.01,
        responseTimeMinutes: 3,
        accountCreatedAt: "2024-06-15",
        activeSessionId: null,
        lastLocationUpdate: null,
        practitionerType: 'wellness-practitioner',
    },
    {
        id: "h-kai-tanaka",
        fullName: "Kai Tanaka",
        avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
        bio: "Reiki master and sound healer. I create a cocoon of vibration and warmth where your nervous system can finally let go. Sessions blend crystal bowls, energy work, and guided meditation.",
        modalities: ["energy-healing", "sound-healing", "meditation"],
        certifications: ["Usui Reiki Master", "Crystal Bowl Sound Therapy"],
        languages: ["English", "Japanese"],
        hourlyRate: 95,
        currency: "USD",
        availabilityStatus: "online",
        isVerified: true,
        yearsExperience: 12,
        avgRating: 4.97,
        totalReviews: 203,
        totalSessions: 580,
        trustScore: 94,
        trustTier: "trusted",
        identityVerified: true,
        credentialsVerified: true,
        backgroundCheck: true,
        cancellationRate: 0.005,
        responseTimeMinutes: 2,
        accountCreatedAt: "2023-11-01",
        activeSessionId: null,
        lastLocationUpdate: null,
        practitionerType: 'heilpraktiker',
    },
    {
        id: "h-elena-rios",
        fullName: "Elena Ríos",
        avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&crop=face",
        bio: "Nervous system specialist. I help your body remember what safety feels like. Using polyvagal-informed techniques, tremoring, and gentle co-regulation — we go at your body's pace, always.",
        modalities: ["nervous-system", "somatic", "emotional-release"],
        certifications: ["Polyvagal-Informed Practitioner", "TRE Provider"],
        languages: ["English", "Spanish", "Portuguese"],
        hourlyRate: 75,
        currency: "USD",
        availabilityStatus: "available_soon",
        isVerified: true,
        yearsExperience: 6,
        avgRating: 4.88,
        totalReviews: 89,
        totalSessions: 210,
        trustScore: 72,
        trustTier: "established",
        identityVerified: true,
        credentialsVerified: true,
        backgroundCheck: false,
        cancellationRate: 0.03,
        responseTimeMinutes: 8,
        accountCreatedAt: "2025-01-10",
        activeSessionId: null,
        lastLocationUpdate: null,
        practitionerType: 'wellness-practitioner',
    },
    {
        id: "h-maya-osei",
        fullName: "Maya Osei",
        avatarUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&h=400&fit=crop&crop=face",
        bio: "Emotional alchemy through breathwork and intuitive energy work. I specialize in helping empaths and sensitives who absorb the world's weight. Let's release what isn't yours to carry.",
        modalities: ["breathwork", "energy-healing", "emotional-release"],
        certifications: ["Conscious Connected Breathwork", "Intuitive Energy Healer"],
        languages: ["English", "French"],
        hourlyRate: 90,
        currency: "USD",
        availabilityStatus: "online",
        isVerified: true,
        yearsExperience: 10,
        avgRating: 4.95,
        totalReviews: 156,
        totalSessions: 420,
        trustScore: 91,
        trustTier: "trusted",
        identityVerified: true,
        credentialsVerified: true,
        backgroundCheck: true,
        cancellationRate: 0.008,
        responseTimeMinutes: 4,
        accountCreatedAt: "2024-03-20",
        activeSessionId: null,
        lastLocationUpdate: null,
        practitionerType: 'wellness-practitioner',
    },
    {
        id: "h-ravi-sharma",
        fullName: "Ravi Sharma",
        avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=face",
        bio: "Meditation guide rooted in Vedic tradition with a modern, trauma-informed approach. Whether you're new to stillness or deepening your practice, I meet you where you are. Fluent in English, Hindi, and German.",
        modalities: ["meditation", "breathwork", "nervous-system"],
        certifications: ["Vedic Meditation Teacher", "Trauma-Informed Yoga"],
        languages: ["English", "Hindi", "German"],
        hourlyRate: 70,
        currency: "USD",
        availabilityStatus: "offline",
        isVerified: true,
        yearsExperience: 15,
        avgRating: 4.90,
        totalReviews: 245,
        totalSessions: 780,
        trustScore: 86,
        trustTier: "trusted",
        identityVerified: true,
        credentialsVerified: true,
        backgroundCheck: true,
        cancellationRate: 0.02,
        responseTimeMinutes: 12,
        accountCreatedAt: "2023-05-01",
        activeSessionId: null,
        lastLocationUpdate: null,
        practitionerType: 'heilpraktiker',
    },
    {
        id: "h-lena-berg",
        fullName: "Lena Berg",
        avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=face",
        bio: "Sound healer and grief space holder. I use voice, bowls, and deep listening to help you metabolize loss. Grief isn't something to fix — it's something to be witnessed. I'll sit with you in it.",
        modalities: ["sound-healing", "grief-holding", "meditation"],
        certifications: ["Sound Healing Practitioner", "Grief Recovery Specialist"],
        languages: ["English", "German"],
        hourlyRate: 80,
        currency: "USD",
        availabilityStatus: "available_soon",
        isVerified: true,
        yearsExperience: 7,
        avgRating: 4.93,
        totalReviews: 112,
        totalSessions: 290,
        trustScore: 45,
        trustTier: "verified",
        identityVerified: true,
        credentialsVerified: true,
        backgroundCheck: false,
        cancellationRate: 0.05,
        responseTimeMinutes: 15,
        accountCreatedAt: "2025-06-01",
        activeSessionId: null,
        lastLocationUpdate: null,
        practitionerType: 'wellness-practitioner',
    },
];

export const SEED_REVIEWS: Record<string, Review[]> = {
    "h-aria-moon": [
        {
            id: "r1",
            seekerName: "Sarah M.",
            rating: 5,
            comment: "Aria held the most beautiful space for me during the worst week of my life. I couldn't stop crying and she just breathed with me until I found stillness. I'll never forget it.",
            createdAt: "2026-02-10",
        },
        {
            id: "r2",
            seekerName: "David K.",
            rating: 5,
            comment: "I was skeptical about breathwork but 20 minutes in I felt my shoulders drop for the first time in months. Aria has a gift.",
            createdAt: "2026-02-05",
        },
        {
            id: "r3",
            seekerName: "Luna F.",
            rating: 5,
            comment: "Exactly what I needed at 2am when the anxiety spiral hit. Knowing someone was there, present, breathing with me — it changed everything.",
            createdAt: "2026-01-28",
        },
    ],
    "h-kai-tanaka": [
        {
            id: "r4",
            seekerName: "Alex W.",
            rating: 5,
            comment: "The sound healing session was transcendent. Kai's bowls created a resonance I felt in my bones. My whole body reorganized. I slept through the night for the first time in weeks.",
            createdAt: "2026-02-12",
        },
        {
            id: "r5",
            seekerName: "Priya N.",
            rating: 5,
            comment: "Kai radiates calm. Even through a screen, his presence is palpable. The Reiki session left me feeling wrapped in light.",
            createdAt: "2026-02-08",
        },
    ],
    "h-elena-rios": [
        {
            id: "r6",
            seekerName: "Jordan T.",
            rating: 5,
            comment: "Elena helped my body release tension I didn't even know I was holding. The polyvagal work is subtle but incredibly powerful. I feel safer in my own skin now.",
            createdAt: "2026-02-11",
        },
        {
            id: "r7",
            seekerName: "Mika S.",
            rating: 4,
            comment: "Really gentle and patient. She let me go at my own pace which I appreciated. Will book again.",
            createdAt: "2026-02-02",
        },
    ],
    "h-maya-osei": [
        {
            id: "r8",
            seekerName: "Chloe R.",
            rating: 5,
            comment: "As an empath, I carry so much that isn't mine. Maya helped me distinguish my feelings from absorbed ones. Life-changing session.",
            createdAt: "2026-02-13",
        },
        {
            id: "r9",
            seekerName: "Ash B.",
            rating: 5,
            comment: "The breathwork with Maya opened something I'd been keeping locked for years. I sobbed and laughed in the same session. Pure alchemy.",
            createdAt: "2026-02-06",
        },
    ],
    "h-ravi-sharma": [
        {
            id: "r10",
            seekerName: "Emma L.",
            rating: 5,
            comment: "Ravi's meditation guidance is unlike anything I've experienced. Not productivity meditation — actual presence. I touched a stillness I didn't know existed in me.",
            createdAt: "2026-02-09",
        },
    ],
    "h-lena-berg": [
        {
            id: "r11",
            seekerName: "Thomas H.",
            rating: 5,
            comment: "Lena sat with my grief without trying to fix it. That's rare. The sound healing wove through me and I could finally breathe again after losing my mother.",
            createdAt: "2026-02-07",
        },
        {
            id: "r12",
            seekerName: "Sofia G.",
            rating: 5,
            comment: "I booked a session expecting to talk. Instead, Lena sang and played bowls and I processed more in 60 minutes than in 6 months of traditional therapy.",
            createdAt: "2026-01-30",
        },
    ],
};
